// Do not edit. This file is machine generated by the Resource DLL Wizard.

library AntiPublic;

{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {DFMFileType} {Unit3.dfm}
{ITE} {RCFileType} {Win64\Release\AntiPublic_DRC.rc}

{$R 'Unit1.dfm' 'Form1:TForm'}
{$R 'Unit2.dfm' 'Form2:TForm'}
{$R 'Unit3.dfm' 'Form3:TForm'}
{$R 'Win64\Release\AntiPublic_DRC.res' 'Win64\Release\AntiPublic_DRC.rc'}

{$E ENU}

begin
end.
